language: c

os:
- linux
- osx

dist: bionic

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - cmake

compiler:
- gcc
- clang

before_script:
- mkdir build
- cd build
- cmake -DENABLE_COVERAGE=1 -DENABLE_TESTS=1 ..

script:
 - make
 - make test

 # Run tests for get_executable_path
 - bash ../test/test_executable_paths.sh ./cwalktest_exe_path

after_success:
- bash <(curl -s https://codecov.io/bash)
